version: '2.1'
services:
 account-mongodb:
    build: mongodb
    ports:
      - 26000:27017
    volumes:
      - /data/db/mongo:/data/db   
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"