#auth-mongodb
spring:
  data:
    mongodb:
      host: ${account-mongodb:39.107.253.90}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
